create table if not exists public.support_messages (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null,
  email text not null,
  message text not null,
  source text not null default 'contact_page',
  status text not null default 'new'
);

create index if not exists support_messages_created_at_idx
  on public.support_messages (created_at desc);

-- Lock down by default.
alter table public.support_messages enable row level security;

-- API route can insert using service-role key.
-- If you also want client-side inserts later, add a specific policy.
